import "@/assets/styles/base.scss";
import Header from "@/components/molecules/Header";
import WithAuthProvider from "@/core/providers/withAuthProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <WithAuthProvider>
        <body className={inter.className}>
          <Header />
          <main className="flex flex-col p-2 min-h-screen">{children}</main>
        </body>
      </WithAuthProvider>
    </html>
  );
}
